### ISSUE TITLE
my own dataset to run eegiza

### ISSUE THREAD

**Issue by Lihwnlp** [lilt/alignment-scripts#13]
Thank you for sharing. I would like to use my own dataset to run eegiza. What should I do?

**Comment by thomasZen** [comment]
Hi @Lihwnlp ,
In this repository you can only find examples how to run [mgiza](https://github.com/moses-smt/mgiza). For eegiza, I think you should look at https://github.com/kellymarchisio/ee-giza.

**Comment by Lihwnlp** [comment]
Thank you for your reply😊. I am here at the link https://github.com/kellymarchisio/ee-giza Coming over (because I couldn't find the issues on that link), I used it https://github.com/kellymarchisio/ee-giza The tutorial ran my own data: I followed the run eegiza. sh script to place my data in the root directory under data/and ran "sh run eegiza. sh de en 1000", but the word alignment results I obtained were very poor (even worse than traditional Giza++), and I want to know which link went wrong. Looking forward to your reply, thank you 🌹🌹🌹
Additionally, running "sh run eegiza. sh de en 1000" seems to generate an error. My environment is Ubantu 18.04, so I chose "bash run eegiza. sh de en 1000"

**Comment by thomasZen** [comment]
Sorry, I don't have context on the ee-giza repository and can't help. (You could try to contact @kellymarchisio and see if she has an idea).

But in general it's a good idea to share more context, e.g. you can share your data set, your input and output files (or a subset) and copy the error messages you get.

I'm closing this issue as I'm not able to help and it's not related to this repository.

**Comment by kellymarchisio** [comment]
Hi @Lihwnlp - yes, please file the issue on the EE-Giza++ repo -- I have just activated the Issues tab. Thanks!
